# Generated by Django 4.0 on 2023-10-25 15:11

from django.db import migrations, models
import django.db.models.deletion
import utils.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credit', models.PositiveIntegerField()),
                ('profile', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='accounts.profile')),
            ],
        ),
        migrations.CreateModel(
            name='SellCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[utils.validators.positive_amount_validator])),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('wallet', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='selled_credits', to='transaction.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='CreditChargeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveIntegerField(validators=[utils.validators.positive_amount_validator])),
                ('request_date', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(blank=True)),
                ('wallet', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='credit_charge_requests', to='transaction.wallet')),
            ],
        ),
        migrations.CreateModel(
            name='NotProcessedCreditChargeRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transaction.creditchargerequest',),
        ),
        migrations.CreateModel(
            name='ProcessedCreditChargeRequest',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('transaction.creditchargerequest',),
        ),
        migrations.AddConstraint(
            model_name='creditchargerequest',
            constraint=models.CheckConstraint(check=models.Q(('amount__gt', 0)), name='positive_charge_amount'),
        ),
    ]
