# Generated by Django 4.0 on 2023-11-14 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wallet',
            options={'ordering': ('pk',)},
        ),
    ]
